package co.edu.iudigital.pos.controllers;

public class UsuarioController {

    // TODO: ENDPOINT CREAR USUARIO VENDEDOR POR PARTE DEL ADMIN

    // TODO: ENDPOINT PARA CONSULTAR VENDEDORES

    // TODO: ENDPOINT PARA CONSULTAR VENDEDOR POR ID

    // TODO: ENDPOINT PARA LOGUEARME


}
